blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/Global-Policy-Lab//pyos_package_lukesherman/discussions
    about: Please ask and answer questions here.
